config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:show, :edit, :update]
  
  get '/accounts/:account_id/projects/:project_id/lists/completed/', to: 'lists#completed', as: "account_project_lists_completed"
  
  resources :accounts, only: [:new, :show, :edit, :create, :update, :index] do
    get 'users', on: :member
    resources :projects do
      resources :conversations
      resources :lists, only: [:create, :update, :destroy, :show, :new] do
        resources :items, only: [:new, :create, :update, :destroy, :show]
      end
    end
    resources :members
    resources :comments
  end
        
  resources :updates      
        
  get '/beta', to: 'pages#beta', as: 'beta'
  get '/help', to: 'pages#help', as: 'help'
  get '/welcome', to: 'accounts#new', as: 'welcome'
  
  resources :subscriptions, only: [:new, :create, :edit, :update]
  
  get '/accounts/:account_id/recently', to: 'accounts#recently', as: 'account_recently'
  get '/accounts/:account_id/createdorder', to: 'accounts#createdorder', as: 'account_createdorder'
  get '/accounts/:account_id/alphabetical', to: 'accounts#alphabetical', as: 'account_alphabetical'

  
  get '/accounts/:account_id/archive', to: 'accounts#archive', as: 'account_project_archive'

  get '/accounts/:account_id/projects/:project_id/cancel', to: 'lists#cancel', as: "account_project_cancel_list", :defaults => { :format => 'js' }
  get '/accounts/:account_id/projects/:project_id/lists/:list_id/cancel', to: 'items#cancel', as: "account_project_list_cancel_item", :defaults => { :format => 'js' }
  
  put '/tasks/sort', to: 'items#sort', as: "sort_tasks"
  
  mount_griddler

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'pages#home'

end

app/models/list.rb
# == Schema Information
#
# Table name: lists
#
#  id          :integer          not null, primary key
#  title       :text
#  status      :text
#  project_id  :integer
#  position    :integer
#  description :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class List < ActiveRecord::Base
  
  belongs_to :project
  has_many :items, dependent: :destroy
  
  has_many :notifications
  has_many :comments
  
  validates :title, presence: true
  
end

app/controllers/lists_controller.rb
include ProjectsHelper
class ListsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authenticate_list, only: [:show]
  # before_filter :verify_active

  def new
    @project = Project.find(params[:project_id])
    @list = @project.lists.build
    
    respond_to do |format|
       format.js
     end
  end
  
  def create
    @project = Project.find(params[:project_id])
    @list = @project.lists.create(list_params)
    
    respond_to do |format|
       format.js
     end
  end
  
  def cancel
    @project = Project.find(params[:project_id])
    @list = @project.lists.build
    
    respond_to do |format|
      format.js
    end
  end

  def update
    @project = Project.find(params[:project_id])
    @list = List.find(params[:id])
    
    respond_to do |format|
      if @list.update(list_params)
        format.js
      end
    end
    
  end
  
  def show
    @list = List.find(params[:id])
    @project = @list.project
    @assignees = return_potential_users_to_assign(@project)
  end

  def completed

    @account = Account.find_by_id(params[:account_id])
    @project = Project.find_by_id(params[:project_id])
    
    @lists = List.where(project_id: @project.id).order(id: :desc)
    
  end


  def destroy
    @list = List.find(params[:id])
    
    respond_to do |format|
      if @list.destroy
        format.js
      end
    end
  end
  
  private
  
    def list_params
      params.require(:list).permit(:title, :status, :description)
    end
    
    def check_for_project_membership(project, user)
      if project.removable == "no"
        # family project -- check to see if the user is a family member
        if Member.where(user_id: user.id, account_id: project.account.id).count > 0
          return true
        else
          return false
        end
      else
        # regular project, check for project membership
        if Member.where(user_id: user.id, project_id: project.id).count > 0
          return true
        else
          return false
        end
      end
    end
    
    def authenticate_list
      list = List.find(params[:id])
      project = list.project
      
      if !check_for_project_membership(project, current_user)
        redirect_to root_path
      end
      
    end
    
    def verify_active
      account = Account.find(params[:account_id])
      if account.active_until < Time.now.utc
        if account.stripe_customer_id
          flash[:subscription_expired] = "Your subscription has expired! Don't worry, your data is perfectly fine, but you'll need to update your payment information -- it looks like there was a problem charging your card on file."
          redirect_to edit_subscription_path
        else
          flash[:subscription_expired] = "Your subscription has expired! Don't worry, your data is perfectly fine, but you'll need to enter your payment information and become a paying subscriber."
          redirect_to new_subscription_path
        end
      end
    end    
    
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_existing_list.html.erb
<% @lists.each do |list| %>

	<div class="sortable_list" data-list-id="<%= @list.id %>">

	<% @list = list %>
	<div class="todo_list_box" id="todo_list_box_for-<%= @list.id %>">
		<div id="todo_list_existing_title-<%= @list.id %>">
			<%= render '/lists/existing_list_headline' %>
		</div>
		<div id="todo_list_edit_title_form-<%= @list.id %>" class="starts_hidden">
			<div class="row new_list_form_row">
				<%= form_for list, url: account_project_list_path(@project.account, @project, @list), method: :put, remote: true, html: {class: "form-inline"} do |f| %>
					<%= f.hidden_field :status, value: "active" %>
					<div class="row">
						
						<div class="form-group">
							<div class="">
						  	<%= f.text_field :title, class: "form-control", id: "inline_edit_list_title", placeholder: "A brand new to-do list!" %>
							</div>
						</div>	
						
						<div class="form-group">

								<%= f.submit "Update", class: "btn btn-default right1em" %>
						</div>		
								

						<div class="form-group" id="link_options">	
							Or: <%= link_to "Cancel my edits", '#', id: "cancel_edit_title_link", remote: true, data: { list_id: @list.id.to_s } %>
							 | <%= link_to 'Delete this list', account_project_list_path(@project.account, @project, @list), method: :delete, remote: true, data: {confirm: 'Are you sure? This cannot be undone.'} %>.</p>

						</div>


				<% end %>


				
				</div>
			</div>
			
		</div>	
		
		
		<div class="todo_list_items">
			
			
			<div>
				<ul class="sortable list list-of-items" id="todo_list_items-<%= list.id %>">
				
					<% list.items.each do |li| %>
						<% if li.status == "active" %>
							<% @li = li %>
							
								<%= render '/items/list_item_actionable', locals: {li: @li} %>

						<% end %>	
					<% end %>
			
				</ul>
			</div>
			

			
			<div id="add_todo_list_item_form-<%= list.id %>">
				
			</div>	
			
			<div id="add_todo_item_link-<%= list.id %>" class="add_todo_item_link">
				<%= render '/items/show_new_item_form_link', locals: {project: @project, list: @list} %>
			</div>
			
		</div>
		
		<div id="completed_todo_items_queue-<%= list.id %>" class="completed_queue starts_hidden">
			<p class="text-muted recently_completed_header">Recently completed to-dos</p>
		</div>	
	
	</div>
	
	</div>
	
<% end %>

app/views/lists/_existing_list_headline.html.erb
<h5 class="todo_list_title">
	<a href="<%= account_project_list_path(@project.account, @project, @list) %>"><strong><%= @list.title %></strong></a>
	<span class="edit_list_title_link_span"><%= link_to "[ Edit ]", '#', id: "edit_list_title_link", remote: true, data: { list_id: @list.id.to_s } %></span>
</h5>

app/views/lists/_new_list.html.erb
<div class="sortable_list" data-list-id="<%= @list.id %>">

	<div class="todo_list_box" id="todo_list_box_for-<%= @list.id %>">
		<div id="todo_list_existing_title-<%= @list.id %>">
			<%= render '/lists/existing_list_headline' %>
		</div>
		<div id="todo_list_edit_title_form-<%= @list.id %>" class="starts_hidden">
			<div class="row new_list_form_row">
				<%= form_for @list, url: account_project_list_path(@project.account, @project, @list), method: :put, remote: true, html: {class: "form-inline"} do |f| %>
					<%= f.hidden_field :status, value: "active" %>
					<div class="row">
					
						<div class="form-group">
							<div class="">
						  	<%= f.text_field :title, class: "form-control", id: "inline_edit_list_title", placeholder: "A brand new to-do list!" %>
							</div>
						</div>	
					
						<div class="form-group">

								<%= f.submit "Update", class: "btn btn-default right1em" %>
						</div>		
							

						<div class="form-group" id="link_options">	
							Or: <%= link_to "Cancel my edits", '#', id: "cancel_edit_title_link", remote: true, data: { list_id: @list.id.to_s } %>
							 | <%= link_to 'Delete this list', account_project_list_path(@project.account, @project, @list), method: :delete, remote: true, data: {confirm: 'Are you sure? This cannot be undone.'} %>.</p>

						</div>


				<% end %>


			
				</div>
			</div>
		
		</div>	

		<div class="todo_list_items">
		
			
			<div>	
				<ul class="sortable list list-of-items" id="todo_list_items-<%= @list.id %>">
				
					<% @list.items.each do |li| %>
						<% if li.status == "active" %>
							<% @li = li %>

								<%= render '/items/list_item_actionable', locals: {li: @li} %>

						<% end %>	
					<% end %>
				</ul>
			</div>
				

		
			<div id="add_todo_list_item_form-<%= @list.id %>">
			
			</div>	
		
			<div id="add_todo_item_link-<%= @list.id %>" class="add_todo_item_link">
				<%= render '/items/show_new_item_form_link', locals: {project: @project, list: @list} %>
			</div>
		
		</div>
	
		<div id="completed_todo_items_queue-<%= @list.id %>" class="completed_queue starts_hidden">
			<p class="text-muted recently_completed_header">Recently completed to-dos</p>
		</div>	

	</div>
	
</div>	

app/views/lists/_new_list_form.html.erb
<div class="row new_list_form_row">
	<%= form_for @list, url: account_project_lists_path(@project.account, @project, @list), method: :post, remote: true, html: {class: "form col-md-11"} do |f| %>
		<%= f.hidden_field :status, value: "active" %>
		<div class="row">
			<div class="form-group">
				<div class="col-md-8">
			  	<%= f.text_field :title, class: "form-control", autofocus: true, placeholder: "A brand new to-do list!" %>
				</div>
	
				<div class="col-md-4">
					<%= f.submit "Add to-do list", class: "btn btn-default btn-sm right1em" %>
					<%= link_to "Cancel", account_project_cancel_list_path(@project.account, @project), :remote => true %>
				</div>
	
			</div>


	<% end %>


	
	</div>
</div>

app/views/lists/_new_todo_list_button.html.erb
<div class="row">
	<%= form_for @list, url: new_account_project_list_path(@project.account, @project), method: :get, remote: true, html: {class: "form col-md-2"} do |f| %>
	<%= f.submit "Make a new to-do list", class: "btn btn-default btn-sm" %>
	<% end %>
</div>

app/views/lists/cancel.js.erb
$("#new_todo_form").empty();
$("#show_new_todo_form_link_box").append("<%= escape_javascript(render 'new_todo_list_button', :locals => {list: @list, project: @project}) %>");

app/views/lists/completed.html.erb
<h3>Completed to-do items for <%= @project.title %></h3>
<span class="invite_new_collaborator_link"><%= link_to "Go back to the project page", account_project_path(@project.account, @project) %></span>
<div class="completed_page_top">
	
</div>

<% completed_count = 0 -%>
<% list_count = 0 -%>
<% @lists.each do |list| -%>
	<% item_queue = [] -%>
	<% list.items.each do |li| -%>
		<% item_queue << li if li.status == "checked" -%>
	<% end -%>
	
	<% if item_queue.count > 0 %>
	<div class="completed_todos_list_title"><h5><%= list.title %></h5></div>
	<div class="completed_todos_list_items">
		<% item_queue.each do |li| %>
		    <% completed_count = completed_count + 1 %>
				<% id_string = "list_item" + li.id.to_s %>
				<div class="checkbox">
					<label>
					<%= check_box_tag :list, "unchecked", true, id: id_string, disabled: true, class: "submittable", data: {checked: li.id} %>

						<% completer = User.find_by_id(li.completed_by) %>
				  	<%= link_to li.title, account_project_list_item_path(@project.account, @project, list, li), class: "todo_item-link" %> <span class="text-muted"> ( Completed by <%= completer.name %> on <%= li.updated_at.to_date.to_formatted_s(:long)%> ) </span>

					</label>
				</div>
			<% end %>	
	</div>	
	<% end %>
	
	
<% end %>	

<% if completed_count == 0 %>
	<div class="empty_completed_explainer">It looks like you haven't completed any to-dos for this project yet!</div>
<% else %>
  <div class="completed_todos_counter text-muted">You've completed <%= completed_count %> <%= ' to-do'.pluralize(completed_count) %>. Nice work!</div>
<% end %>

app/views/lists/create.html.erb
<h1>Lists#create</h1>
<p>Find me in app/views/lists/create.html.erb</p>

app/views/lists/create.js.erb
$("#hidden_new_todo_form").toggle();
$("#show_new_todo_form_link").toggle();
$("#new_todo_form").empty();
$("#show_new_todo_form_link_box").append("<%= escape_javascript(render 'new_todo_list_button', :locals => {list: @list, project: @project}) %>");
$("#existing_project_todo_section").prepend("<%= escape_javascript(render 'new_list', :locals => {list: @list, project: @project}) %>");
$("body").trigger('loadSortable');

app/views/lists/destroy.js.erb
$("#todo_list_box_for-<%= escape_javascript(@list.id.to_s) %>").remove();

app/views/lists/new.js.erb
$("#new_todo_form").append("<%= escape_javascript(render 'new_list_form', :locals => {list: @list, project: @project}) %>");
$("#show_new_todo_form_link_box").empty();

app/views/lists/show.html.erb
<h3><%= @list.project.title %></h3>
<span class="invite_new_collaborator_link"><%= link_to "Go back to the project page", account_project_path(@project.account, @project) %></span>
<div class="completed_page_top">
</div>


<div class="list_page_todos_section">
	
	<%= render 'new_list' %>
	
</div>

app/views/lists/update.js.erb
$("#todo_list_existing_title-<%= escape_javascript(@list.id.to_s) %>").empty();
$("#todo_list_existing_title-<%= escape_javascript(@list.id.to_s) %>").toggle();
$("#todo_list_existing_title-<%= escape_javascript(@list.id.to_s) %>").append("<%= escape_javascript(render '/lists/existing_list_headline', :locals => {list: @list, project: @project}) %>");
$("#todo_list_edit_title_form-<%= escape_javascript(@list.id.to_s) %>").toggle();