config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:show, :edit, :update]
  
  get '/accounts/:account_id/projects/:project_id/lists/completed/', to: 'lists#completed', as: "account_project_lists_completed"
  
  resources :accounts, only: [:new, :show, :edit, :create, :update, :index] do
    get 'users', on: :member
    resources :projects do
      resources :conversations
      resources :lists, only: [:create, :update, :destroy, :show, :new] do
        resources :items, only: [:new, :create, :update, :destroy, :show]
      end
    end
    resources :members
    resources :comments
  end
        
  resources :updates      
        
  get '/beta', to: 'pages#beta', as: 'beta'
  get '/help', to: 'pages#help', as: 'help'
  get '/welcome', to: 'accounts#new', as: 'welcome'
  
  resources :subscriptions, only: [:new, :create, :edit, :update]
  
  get '/accounts/:account_id/recently', to: 'accounts#recently', as: 'account_recently'
  get '/accounts/:account_id/createdorder', to: 'accounts#createdorder', as: 'account_createdorder'
  get '/accounts/:account_id/alphabetical', to: 'accounts#alphabetical', as: 'account_alphabetical'

  
  get '/accounts/:account_id/archive', to: 'accounts#archive', as: 'account_project_archive'

  get '/accounts/:account_id/projects/:project_id/cancel', to: 'lists#cancel', as: "account_project_cancel_list", :defaults => { :format => 'js' }
  get '/accounts/:account_id/projects/:project_id/lists/:list_id/cancel', to: 'items#cancel', as: "account_project_list_cancel_item", :defaults => { :format => 'js' }
  
  put '/tasks/sort', to: 'items#sort', as: "sort_tasks"
  
  mount_griddler

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'pages#home'

end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  title       :text
#  removable   :string
#  description :text
#  account_id  :integer
#  status      :text
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Project < ActiveRecord::Base
  
  # Projects / Users
  has_many :members
  has_many :users, through: :members
  has_many :lists, dependent: :destroy
  has_many :comments
  has_many :notifications
  has_many :conversations
  
  belongs_to :account
  
  validates :title, presence: true
end

app/controllers/projects_controller.rb
include ProjectsHelper
class ProjectsController < ApplicationController
  # we get to use current_user without checking because we require log-in in this controller
  before_filter :authenticate_user!
  before_filter :check_editable, only: [:edit]
  before_filter :authenticate_project, only: [:show, :edit]
  # before_filter :verify_active
  
  def index
  end

  def new
    @account = Account.find_by_id(params[:account_id])
    @project = @account.projects.build unless @account.nil?
    
    respond_to do |format|
      if @account.nil?
        format.html { redirect_to new_account_path }
      else
        format.html { render 'new' }
      end
    end
  end
  
  def show
    @project = Project.where(account: params[:account_id], id: params[:id])[0]
    @account = Account.find_by_id(params[:account_id])
    
    # For lists & items
    @list = @project.lists.new
    @lists = List.where(project_id: @project.id, status: "active").order(id: :desc)
    @assignees = return_potential_users_to_assign(@project)
    
    # for conversations
    @conversations = @project.conversations.limit(5).order('created_at DESC')
    
    @page_title = "- #{@project.title}"
    
    if @project.status == "garage"
      @garage = true
    end
    
    respond_to do |format|
      if @project.nil?
        format.html { redirect_to root_path }
      else
        if @project_check == false
          format.html { redirect_to root_path }
        else
          format.html { render 'show' }
        end
      end
    end
  end



  def create
    
    @account = Account.find_by_id(params[:account_id])
    @project = @account.projects.create(project_params)
    
    # now we need to associate the user that created it
    @new_member = Member.add_user_to_project(current_user, @project)
    @new_member.save!
    
    # check to see if we're supposed to associate anyone else
    if params[:family_share]
      family_members = Member.where(account_id: @account.id)
      family_members.each do |fm|
        usr = fm.user
        if usr
          mem = Member.add_user_to_project(usr, @project) unless usr == current_user
          # send email
        elsif fm.email && fm.email != ""
          mem = Member.add_pending_user_to_project(fm.email, fm.name, @project)
          # send email
        end
        
      end
    end
    
    respond_to do |format|
      if @project.save
        format.html { redirect_to account_project_path(@account, @project) }
      else
        format.html { render action: "new" }
      end
    end
    
  end

  def edit
    @project = Project.find_by_id(params[:id])
    @account = Account.find_by_id(params[:account_id])
    
  end

  def update
    @project = Project.find(params[:id])
    @account = @project.account
    logger.info @project.title
    
    respond_to do |format|
      if @project.update(project_params)
        if @project.status == "garage"
          format.html { redirect_to root_path, notice: 'OK: We stashed that project in the garage.'}
        else
          format.html { redirect_to account_project_path(@account, @project), notice: 'Project updated!' }
          format.js { render 'update' }
        end  
      else
        format.html { render action: "edit" }
      end
    end
    
  end
  
  def destroy
    @project = Project.find(params[:id])
    
    if @project.removable == "no"
      @removable = "yes"
    end

    @members_to_delete = @project.members
    
      if @project.delete  
        
        @members_to_delete.each do |m|
          m.delete
        end
        
        if @removable == "yes"
          redirect_to root_path, flash: {warning: 'OK, family member removed.'}
        else
          redirect_to root_path, flash: {warning: 'OK, that project has gone the way of the dodo.'}
        end
      else
        redirect_to root_path, flash: {danger: 'Uh, oh, something went wrong.' }  
      end # project delete

    
  end
  
  private

    def project_params
      params.require(:project).permit(:title, :description, :status, :members_attributes => [:id, :email, :name, :user_id])
    end
  
    def check_editable
      project = Project.find_by_id(params[:id])
      if project.removable == "no"
        redirect_to root_path
      end
    end
    
    def check_for_project_membership(project, user)
      if project.removable == "no"
        # family project -- check to see if the user is a family member
        if Member.where(user_id: user.id, account_id: project.account.id).count > 0
          return true
        else
          return false
        end
      else
        # regular project, check for project membership
        if Member.where(user_id: user.id, project_id: project.id).count > 0
          return true
        else
          return false
        end
      end
    end
    
    def authenticate_project
      project = Project.find(params[:id])
      if !check_for_project_membership(project, current_user)
        redirect_to root_path
      end
    end
    
    def verify_active
      account = Account.find(params[:account_id])
      if account.active_until < Time.now.utc
        if account.stripe_customer_id
          flash[:subscription_expired] = "Your subscription has expired! Don't worry, your data is perfectly fine, but you'll need to update your payment information -- it looks like there was a problem charging your card on file."
          redirect_to edit_subscription_path
        else
          flash[:subscription_expired] = "Your subscription has expired! Don't worry, your data is perfectly fine, but you'll need to enter your payment information and become a paying subscriber."
          redirect_to new_subscription_path
        end            
      end
    end
    
  
end

app/helpers/projects_helper.rb
module ProjectsHelper

  def return_potential_users_to_assign(project)
    #[{"id"=>1, "name"=>"Jason Preston"}]
    if project.removable == "no"
      members = Member.where.not(user_id: nil).where(account_id: project.account.id)
    else  
      members = Member.where.not(user_id: nil).where(project_id: project.id)
    end  
    user_names_and_ids_hash = Hash.new
    user_names_and_ids_hash["Assign it"] = 0
    members.each do |member|
      name = member.user.name 
      id = member.user.id
      user_names_and_ids_hash[name] = id
    end

    return user_names_and_ids_hash
  end
  
  
  def check_for_and_issue_assigned_todo_notifications(item)
    if item.user
      logger.info("Email notification logic")
      assigning_user = User.find(item.created_by)
      # If there's a user it's assigned to someone, and they should get a notification
      # IF the user has enabled notifications. [ "immediate", "off", "digest" ]
      # Also we should only do immediate e-mails for new to-dos with due dates, and if the users are different
      if item.user.email_preference == "immediate"
        if assigning_user != item.user
          if item.due
            # send notification
            if NotificationMailer.new_todo_assigned_to_user(item, item.user, assigning_user).deliver_later
              # create notification object, mark as sent
              notification_string = assigning_user.name + " assigned you a to-do: " + item.title 
              @notification = Notification.new(user_id: item.user.id, creator_id: item.created_by, notification: notification_string, email_status: "sent", status: "new", item_id: item.id)
              @notification.save
            end # delivery check  
          end  
        else
          # save a self-notifcation for fun
          notification_string = "You assigned yourself a to-do: " + item.title 
          @notification = Notification.new(user_id: item.user.id, creator_id: item.created_by, notification: notification_string, email_status: "sent", status: "new", item_id: item.id) 
          @notification.save 
        end # self-sender check  
      elsif item.user.email_preference == "digest"
        # queue notification
        # notification_string: "This user has assigned you a to-do"
        # Notification.new(user_id: item.user.id, creator_id: item.created_by, notification: notification_string, email_status: "queued", status: "new")
      else # "off"
        # no email notification -- tell the Notification object it's already sent
        # create notification object, mark as sent
        notification_string = assigning_user.name + " assigned you a to-do: " + item.title 
        @notification = Notification.new(user_id: item.user.id, creator_id: item.created_by, notification: notification_string, email_status: "sent", status: "new", item_id: item.id)
        @notification.save
      end  
      
    end
  end
  
  # Warning: this thing is a beast.
  # Need to re-factor at some point.
  
  def check_for_and_issue_completed_todo_notifications(item)
    if item.user
      logger.info("Todo completed notification logic")
      assigning_user = User.find(item.created_by)
      completing_user = User.find(item.completed_by)
      # If someone completes a to-do, the assigning user should be notified
      # IF the user has enabled notifications. [ "immediate", "off", "digest" ]
      # AND IF the completing user is not the assigning user
      if assigning_user.email_preference == "immediate"
        if assigning_user != completing_user
          # send notification
          if NotificationMailer.assigned_user_completed_todo(item, completing_user, assigning_user).deliver_later
            # create notification object, mark as sent
            notification_string = completing_user.name + " completed a to-do you assigned: " + item.title 
            @notification = Notification.new(user_id: item.user.id, creator_id: item.created_by, notification: notification_string, email_status: "sent", status: "new", item_id: item.id)
            @notification.save
          end # check for mail delivery  
        else
          # save a self-notifcation for fun
          notification_string = "You completed a to-do: " + item.title 
          @notification = Notification.new(user_id: item.created_by, creator_id: item.created_by, notification: notification_string, email_status: "sent", status: "new", item_id: item.id)
          @notification.save
        end # self-sender check
      elsif item.user.email_preference == "digest"
        # queue notification
        # notification_string: "This user has assigned you a to-do"
        # Notification.new(user_id: item.user.id, creator_id: item.created_by, notification: notification_string, email_status: "queued", status: "new")
      else # "off"
        # no email notification -- tell the Notification object it's already sent
        notification_string = completing_user.name + " completed a to-do you assigned: " + item.title 
        @notification = Notification.new(user_id: item.created_by, creator_id: item.created_by, notification: notification_string, email_status: "sent", status: "new", item_id: item.id)
        @notification.save 
      end  
      
    end
  end

end

app/views/projects/_conversations_loop.html.erb
<div id="conversations_box">	
	<table class="table conversations_table table-condensed table-striped">
		<tbody>
		<% @conversations.each do |c| %>
			<tr>
				<td>
					<strong>
						<%= link_to c.title, account_project_conversation_path(@account, @project, c), class: "conversation_link" %>
					</strong>
					<% preview = sanitize raw(c.content), tags: %w(strong em a) %>
					<%= truncate(preview, length: 45) %>
				</td>
				<td>
					<span class="text-muted">Posted by <%= c.user.name.split(" ")[0] if c.user.name %></span>
				</td>
				<td>
					<span class="convo_comment_count">
						<a href="<%= account_project_conversation_path(@account, @project, c) %>">
							<%= c.comments.count %> <%= 'comment'.pluralize(c.comments.count) %>
						</a>
					</span>
				</td>	
			</tr>
		<% end -%>
		</tbody>
	</table>
</div>

app/views/projects/_existing_project_headline.html.erb
<h2><%= @project.title %> <span class="edit_project_headline_link"><%= link_to "[ Edit ]", '#', id: "edit_project_headline_link", remote: true %></span></h2>

<div class="">
	<h5 class="project_description"><%= @project.description %></h5>
</div>

app/views/projects/_project_headline.html.erb
<div class="project_headline_box">
	<div id="project_headline">
		<%= render '/projects/existing_project_headline' %>
	</div>
	
	<div id="edit_project_headline_form" class="starts_hidden">
		<div class="row edit_project_title_row">
			<%= form_for @project, url: account_project_path(@project.account, @project), method: :put, remote: true, html: {class: "form-inline"} do |f| %>

					
					<div class="form-group">
						<div class="">
					  	<%= f.text_field :title, class: "form-control", id: "inline_edit_project_title" %>
						</div>
					</div>	
					
					<div class="form-group">
						<div class="">
					  	<%= f.text_field :description, class: "form-control right1em", id: "inline_edit_project_description" %>
						</div>
					</div>
					
					<div class="form-group">
							<%= f.submit "Update", class: "btn btn-default right1em" %>
					</div>		
							

					<div class="form-group" id="link_options">	
						Or: <%= link_to "Cancel my edits", '#', id: "cancel_edit_project_headline_link", remote: true, data: { list_id: @list.id.to_s } %>
					</div>

	
			<% end %>
						
		</div>
		
	</div>
	
</div>	

app/views/projects/_project_mini_footer.html.erb
<div id="access_edit_project">
	<p class="help-block"><%= link_to "[ Update project settings ]", '#', id: "access_edit_project_link", remote: true, data: { project_status: "status_link" } %></p>
</div>

<div id="hidden_settings_form">

	<div class="row">
	<h5 class="left-adjust">Project Settings</h5>	
	<%= form_for @project, url: account_project_path(@account, @project), method: :put , html: {class: "form"} do |f| %>
		
		
		<div class="form-group">
			
			<div class="control-label"></div>
			<div class="radio col-sm-10">
				<label>
				<%= f.radio_button :status, "active", {value: @project.status} %>
				<div class="">
			  	This project is in the house: add to-dos, conversations, etc.
				</div>
				</label>
			</div>


			<div class="control-label"></div>
			<div class="radio col-sm-10">
				<label>
				<%= f.radio_button :status, "garage", {value: @project.status} %>
				<div class="">
			  	In the garage; everything will stay exactly as-is in case you want to pull it out later, but it won't take up space on your dashboard.
				</div>
				</label>
			</div>	

		</div>
		
		<div class="actions col-sm-12">
	    <%= f.submit "Update the project", class: "btn btn-default" %>
			<span class="cancel_new_project"> <%= link_to "Nevermind, cancel...", '#', id: "hide_edit_project_link", remote: true, data: { edit_status_hide: "hide_link" } %></span>
			
			<span class="delete_project_link col-sm-offset-3">
			Or, you can <%= link_to 'delete the entire project permanently', account_project_path(@account, @project), method: :delete, data: {confirm: 'Are you sure? This cannot be undone.'} %>.
			</span>
			
	  </div>
		
	<% end %>
	

</div>

app/views/projects/create.html.erb
<h1>Projects#create</h1>
<p>Find me in app/views/projects/create.html.erb</p>

app/views/projects/edit.html.erb
<%= form_for @project, url: account_project_path(@account, @project), method: :put , html: {class: "form new_project"} do |f| %>

<% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
        <% @account.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>

	<div class="form-group">
	  <div class="controls"><%= f.text_field :title, autofocus: true, class: "form-control input-lg", placeholder: "Title The New Project" %></div>
	</div>

	<div class="form-group">
	  <div class="controls"><%= f.text_area :description, class: "form-control", placeholder: "(Optional) A short project description" %></div>
	</div>


  <div class="actions">
    <%= f.submit "Update the project", class: "btn" %>
  </div>
<% end %>

app/views/projects/index.html.erb
<h1>Projects#index</h1>
<p>Find me in app/views/projects/index.html.erb</p>

app/views/projects/new.html.erb
<div class="row">
<div class="new_project_page_box col-md-8 col-md-offset-2">
	
	<%= form_for @project, url: account_projects_path(@account, @project) , html: {class: "form new_project"} do |f| %>

	<% if @project.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this account from being saved:</h2>

	      <ul>
	        <% @account.errors.full_messages.each do |msg| %>
	            <li><%= msg %></li>
	        <% end %>
	      </ul>
	    </div>
	<% end %>

		<div class="form-group">
		  <div class="controls"><%= f.text_field :title, autofocus: true, class: "form-control input-lg", placeholder: "Title The New Project" %></div>
		</div>

		<div class="form-group">
		  <div class="controls"><%= f.text_area :description, class: "form-control", rows: 4, placeholder: "(Optional) A short project description" %></div>
		</div>
		
		<%= f.hidden_field :status, value: "active" %>

		<div class="form-group">

			<div class="checkbox">
				<label>
				<%= check_box_tag :family_share, "family_share", false %>
			  	Automatically add all family members as collaborators.
				</label>
			</div>	
			

		</div>


	  <div class="form-group">
			<div class="controls">
	    <%= f.submit "Create a new project", class: "btn btn-default" %>
			<span class="cancel_new_project">Or <%= link_to "nevermind, cancel...", root_path %></span>
			</div>

	  </div>


	<% end %>

</div>
</div>

app/views/projects/show.html.erb
<div class="project_page">

	<% if @garage %>
		<p class="garage_notice">
			This project has been stashed in the garage! That means it's frozen in time unless you choose to make it active in the project settings below, after which it will appear in your dashboard again.
		</p>
	<% end %>

	<div class="project_page_top">
		
		<div id="page_top_collab_invite">
			<% if @project.users.first == current_user %>
				<% if @project.removable != "no" %>
					<% if !@garage %>
						<span class="invite_new_collaborator_link">
						<%= link_to "Invite a new collaborator", new_account_member_path(@account, project: @project.id) %>
						</span>
					<% end %>
				<% end %>
			<% end %>
		</div>
	
		<%= render 'projects/project_headline' %>
		
	</div>	

	<h4 class="todo_header">Conversations</h4>
	
	<span class="see_conversations">
		<%= link_to "See all conversations on this project...", account_project_conversations_path(@account, @project) %>
	</span>
	
	<div class="new_conversation_button">
		<a href="<%= new_account_project_conversation_path(@account, @project) %>">
			<button type="button" class="btn btn-default btn-sm">Start a new conversation</button>
		</a>
	</div>	
	

	
		<%= render 'conversations_loop' %>
	

	<h4 class="todo_header">To-do lists</h4>
	<div id="project_todo_section">
	
		<div id="show_new_todo_form_link_box">
			<%= render '/lists/new_todo_list_button', locals: {lists: @list, project: @project, account: @account} %>
		</div>
	
		<div id="new_todo_form">

		</div> 
	
	</div>	<!-- end todo section -->

	<div id="existing_project_todo_section">

			<%= render '/lists/existing_list', locals: {lists: @lists, project: @project} %>

	</div>
	
	<div class="completed_todos">
		<%= link_to "See completed to-dos for this project...", account_project_lists_completed_path(@account, @project) %>
	</div>

	<div class="project_mini_footer">
		<% if @project.removable != "no" %>
			<%= render 'project_mini_footer', locals: {account: @account, project: @project} %>
		<% end %>
	
	</div>

	<div class="family_mini_footer">
	
		<% if @project.removable == "no" %>
			<% if @project.users.first != current_user %>
				<div id="access_edit_family_member_project">
					<p class="help-block"><%= link_to "[ Show options ]", '#', id: "access_edit_family_member_project_link", remote: true, data: { family_member: "options_link" } %></p>
				</div>
	
	
					<div id="edit_family_member_project">
						<p><%= link_to "[ Hide this option ]", '#', id: "access_edit_family_member_project_link", remote: true, data: { family_options: "hide_options_link" } %></p>
						<p class="help-block">You can <%= link_to 'remove this person permanently', account_project_path(@account, @project), method: :delete, data: {confirm: 'Are you sure? This cannot be undone.'} %> from your family.</p>
					</div>
			<% end %>
		<% end %>
	</div>	

</div>

app/views/projects/update.html.erb
<h1>Projects#update</h1>
<p>Find me in app/views/projects/update.html.erb</p>

app/views/projects/update.js.erb
$('#project_headline').empty();
$('#project_headline').toggle();
$('#edit_project_headline_form').toggle();
$('#project_headline').append("<%= escape_javascript(render '/projects/existing_project_headline', :locals => {project: @project}) %>");