config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:show, :edit, :update]
  
  get '/accounts/:account_id/projects/:project_id/lists/completed/', to: 'lists#completed', as: "account_project_lists_completed"
  
  resources :accounts, only: [:new, :show, :edit, :create, :update, :index] do
    get 'users', on: :member
    resources :projects do
      resources :conversations
      resources :lists, only: [:create, :update, :destroy, :show, :new] do
        resources :items, only: [:new, :create, :update, :destroy, :show]
      end
    end
    resources :members
    resources :comments
  end
        
  resources :updates      
        
  get '/beta', to: 'pages#beta', as: 'beta'
  get '/help', to: 'pages#help', as: 'help'
  get '/welcome', to: 'accounts#new', as: 'welcome'
  
  resources :subscriptions, only: [:new, :create, :edit, :update]
  
  get '/accounts/:account_id/recently', to: 'accounts#recently', as: 'account_recently'
  get '/accounts/:account_id/createdorder', to: 'accounts#createdorder', as: 'account_createdorder'
  get '/accounts/:account_id/alphabetical', to: 'accounts#alphabetical', as: 'account_alphabetical'

  
  get '/accounts/:account_id/archive', to: 'accounts#archive', as: 'account_project_archive'

  get '/accounts/:account_id/projects/:project_id/cancel', to: 'lists#cancel', as: "account_project_cancel_list", :defaults => { :format => 'js' }
  get '/accounts/:account_id/projects/:project_id/lists/:list_id/cancel', to: 'items#cancel', as: "account_project_list_cancel_item", :defaults => { :format => 'js' }
  
  put '/tasks/sort', to: 'items#sort', as: "sort_tasks"
  
  mount_griddler

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'pages#home'

end

app/models/item.rb
# == Schema Information
#
# Table name: items
#
#  id           :integer          not null, primary key
#  title        :text
#  list_id      :integer
#  user_id      :integer
#  due          :datetime
#  status       :text
#  created_by   :integer
#  completed_by :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  flep         :string
#  position     :integer
#

class Item < ActiveRecord::Base

  belongs_to :list
  belongs_to :user
  
  has_many :notifications
  has_many :comments
  
  validates :title, presence: true
  
  default_scope { order("position ASC") }

end

app/controllers/items_controller.rb
include ItemsHelper
include ProjectsHelper
include ApplicationHelper
class ItemsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :authenticate_item, only: [:update, :edit, :show]
  # before_filter :verify_active, only: [:update, :edit, :show]
  
  def new
    @list = List.find(params[:list_id])
    @project = @list.project
    
    @assignees = return_potential_users_to_assign(@project)
    
    @item = @list.items.build
  end

  def create
    @list = List.find(params[:list_id])
    @project = @list.project
    @assignees = return_potential_users_to_assign(@project)
    
    @li = @list.items.create(item_params)
    @list.status = "active"
    @list.save
    
    @item = @list.items.build
    
    if @li.due
      if @li.user
        notify_users = []
        notify_users << @li.user.id unless @li.user == current_user
        logger.info(notify_users)
        check_for_and_issue_notifications_for(@li, notify_users, "new_todo_assigned")
      end
    end
    
    respond_to do |format|
      format.js
    end
  end

  def update
    @list = List.find(params[:list_id])
    @project = @list.project
    @assignees = return_potential_users_to_assign(@project)
    
    @li = Item.find(params[:id])
    @li.update(item_params)
    
    if params[:action_to_take] == "update"
      @action = "updated"
    elsif params[:action_to_take] == "individual_update_info"
      @action = "updated_individually"
    elsif params[:action_to_take] == "individual_update"
      @action = "individual_update"  
    elsif params[:action_to_take] == "check_and_move"
      @action = "checked"
    elsif params[:action_to_take] == "uncheck_and_move"
      @action = "unchecked"
    end
    
    # If the to-do has been checked, issue notification
    if @action == "checked"
       notify_users = []
       # notify the user who created the to-do, unless it's the same as the user who completed it
       notify_users << @li.created_by unless @li.created_by == current_user.id
       check_for_and_issue_notifications_for(@li, notify_users, "todo_completed")
     end
    
    # Set the list to completed if this is the last to-do
    # or re-activate it if needed
    active_todo_count = Item.where(list_id: @list.id, status: "active").count
    if active_todo_count < 1
      @list.status = "completed"
      @list.save
    elsif active_todo_count > 0
      @list.status = "active"
      @list.save
    end
    
    respond_to do |format|
      if @action == "checked"
        format.js {render 'checked'}
      elsif @action == "unchecked"
        format.js {render 'unchecked' }  
      elsif @action == "individual_update"
        format.js {render 'nada' }  
      elsif @action == "updated_individually"
        format.js {render 'individual' }  
      else
        format.js {render 'update'}
      end
          
    end
  end
  
  def sort
    logger.info("need valid data")
    params[:order].each do |key,value|
      Item.find(value[:id]).update_attribute(:position,value[:position])
    end
    render :nothing => true
  end

  def edit
  end
  
  def show
    @item = Item.find(params[:id])
    @list = @item.list
    @project = @list.project
    @li = @item
    @assignees = return_potential_users_to_assign(@project)   
    
    @page_title = "- #{@item.title}"
    
    # build for comment notification & display
    @notifiable_users = @project.users 
    @notifiable_users_count = count_notifiable_users(@notifiable_users)
    @default_notify_users = return_default_users_to_notify(@item)
    @comment = @item.comments.build
    @existing_comments = @item.comments.order(:id)
    
  end

  def destroy
    @li = Item.find(params[:id])
    
    respond_to do |format|
      if @li.destroy
        format.js
      end
    end
  end
  
  def cancel
    @project = Project.find(params[:project_id])
    @list = List.find(params[:list_id])
    
    respond_to do |format|
      format.js
    end
  end  
  
  private
  
    def item_params
      params.require(:item).permit(:title, :status, :due, :user_id, :created_by, :completed_by, :flep)
    end
    
    def check_for_project_membership(project, user)
      if project.removable == "no"
        # family project -- check to see if the user is a family member
        if Member.where(user_id: user.id, account_id: project.account.id).count > 0
          return true
        else
          return false
        end
      else
        # regular project, check for project membership
        if Member.where(user_id: user.id, project_id: project.id).count > 0
          return true
        else
          return false
        end
      end
    end
    
    def authenticate_item
      item = Item.find(params[:id])
      project = item.list.project
      
      if !check_for_project_membership(project, current_user)
        redirect_to root_path
      end
      
    end
    
    def verify_active
      account = Account.find(params[:account_id])
      if account.active_until < Time.now.utc
        if account.stripe_customer_id
          flash[:subscription_expired] = "Your subscription has expired! Don't worry, your data is perfectly fine, but you'll need to update your payment information -- it looks like there was a problem charging your card on file."
          redirect_to edit_subscription_path
        else
          flash[:subscription_expired] = "Your subscription has expired! Don't worry, your data is perfectly fine, but you'll need to enter your payment information and become a paying subscriber."
          redirect_to new_subscription_path
        end
      end
    end    
  
end

app/helpers/items_helper.rb
module ItemsHelper

  
end

app/views/items/_list_item_actionable.html.erb
<li data-item-id="<%= @li.id %>">
	<div id="list_item_actionable_box-<%= @li.id %>" class="list_item_actionable_box_margin">
		<%= render '/items/list_item_actionable_content', locals: {li: @li} %>
	</div>
</li>

app/views/items/_list_item_actionable_content.html.erb
<div id="list_item_actionable-<%= @li.id %>" data-list-container="<%= @li.id.to_s %>">
	<%= form_for @li, url: account_project_list_item_path(@project.account, @project, @list, @li), method: :put, remote: true, html: {class: "form-inline"} do |f| %>
	<%= hidden_field_tag :action_to_take, "check_and_move" %>
	<div class="checkbox">
		<% id_string = "list_item" + @li.id.to_s %>
		<% if @li.status == "active" -%>
			<%= f.hidden_field :completed_by, value: current_user.id %>
		<% else -%>
			<%= f.hidden_field :completed_by, value: nil %>
		<% end -%>
		<label>
		<%= f.check_box :status, {id: id_string, class: "submittable", data: {checked: @li.id} }, "checked", "active" %>	

	  	<%= link_to @li.title, account_project_list_item_path(@project.account, @project, @list, @li), class: "todo_item-link" %>
			
			<% if @li.user %>
				<span class="todo_assigned_person_label">
					<%= @li.user.name %></a>
				</span>
			<% end %>	
			
			<% if @li.due %>
				<span class="todo_due_date_label">	
					<%= @li.due.to_date.to_formatted_s(:long) %>
				</span>	
			<% end %>
			
			<% if @li.comments.count > 0 %>
				<span class="todo_comment_count_link">	
					<a href="<%= account_project_list_item_path(@project.account, @project, @list, @li) %>">
						(<%= @li.comments.count %> <%= 'comment'.pluralize(@li.comments.count) %>)
					</a>
				</span>	
			<% end %>
			
			<% linkstring = '#list_item_actionable-' + @li.id.to_s -%>
			
			<%= link_to "Edit", "#{linkstring}", id: "show_edit_item_form_link",  data: { item_id: @li.id.to_s } %>

		</label>
	</div>
	<% end %>
</div>

<div class="row new_list_item_form_row starts_hidden" id="update_list_item_form-<%= @li.id %>">
	<%= form_for @li, url: account_project_list_item_path(@project.account, @project, @list, @li), method: :put, remote: true, html: {class: "form-inline"} do |f| %>
		<%= f.hidden_field :status, value: "active" %>
		<%= hidden_field_tag :action_to_take, "update" %>

			<div class="form-group col-sm-6">
			  	<%= f.text_field :title, class: "form-control input-sm", id: "todo_item_input", placeholder: "Add a to-do item" %>
			</div>	
				
			<div class="form-group">
				<%= f.select :user_id, options_for_select(@assignees, @li.user_id), {}, :class => "input-sm form-control assign_user_select" %>
			</div>		
			
			<div class="form-group">
				<div class="input-group date_picker_field" id="new_item_date_field" >
					<% due_string = @li.due.strftime("%d/%m/%Y") if @li.due %>
					<%= f.text_field :due, value: due_string, class: "form-control input-sm", id: "todo_due_date_input" %>
					<span class="input-group-addon">
						<span class="fa fa-calendar"></i>
					</span>
				</div>
			</div>
	
			<div class="form-group">
				<%= f.submit "Update", class: "btn btn-default right1em btn-sm" %>
			</div>
	<% end %>
	
	<div class="new_list_item_cancel_link">
		<% linkstring = '#list_item_actionable-' + @li.id.to_s -%>
		<%= link_to "Cancel my edits", "#{linkstring}", id: "cancel_edit_item_link", data: { item_id: @li.id.to_s } %> or
		<%= link_to 'Delete this item', account_project_list_item_path(@project.account, @project, @list, @li), method: :delete, remote: true %>.</p>
	</div>	
	
</div>

app/views/items/_list_item_inactive.html.erb
<div id="list_item_inactive-<%= @li.id %>">
	<%= form_for @li, url: account_project_list_item_path(@project.account, @project, @list, @li), method: :put, remote: true, html: {class: "form-inline"} do |f| %>
	<%= hidden_field_tag :action_to_take, "uncheck_and_move" %>
	<div class="checkbox">
		<% id_string = "list_item" + @li.id.to_s %>
		<% if @li.status == "active" -%>
			<%= f.hidden_field :completed_by, value: current_user.id %>
		<% else -%>
			<%= f.hidden_field :completed_by, value: nil %>
		<% end -%>
		<label>
		<%= f.check_box :status, {id: id_string, class: "submittable", data: {checked: @li.id} }, "checked", "active" %>

			<% completer = User.find_by_id(@li.completed_by) %>
	  	<%= link_to @li.title, account_project_list_item_path(@project.account, @project, @list, @li), class: "completed_todo" %> <span class="text-muted"> ( Completed by <%= completer.name %> on <%= @li.updated_at.to_date.to_formatted_s(:long)%> ) </span>

		</label>
	</div>
	<% end %>
</div>

app/views/items/_list_item_individual.html.erb
<div id="list_item_actionable-<%= @li.id %>" class="list_item_individual_todo_content" data-list-container="<%= @li.id.to_s %>">
	<%= form_for @li, url: account_project_list_item_path(@project.account, @project, @list, @li), method: :put, remote: true, html: {class: "form-inline"} do |f| %>
	
	<%= hidden_field_tag :action_to_take, "individual_update" %>
	<div class="checkbox">
		<% id_string = "list_item" + @li.id.to_s %>
		<% if @li.status == "active" -%>
			<%= f.hidden_field :completed_by, value: current_user.id %>
		<% else -%>
			<%= f.hidden_field :completed_by, value: nil %>
		<% end -%>	
		<label>
		<%= f.check_box :status, {id: id_string, class: "submittable" }, "checked", "active" %>

	  	<%= link_to @li.title, account_project_list_item_path(@project.account, @project, @list, @li), class: "todo_item-link" %>
			
			<% if @li.user %>
				<span class="todo_assigned_person_label">
					<%= @li.user.name %></a>
				</span>
			<% end %>	
			
			<% if @li.due %>
				<span class="todo_due_date_label">	
					<%= @li.due.to_date.to_formatted_s(:long) %>
				</span>	
			<% end %>
			
			<%= link_to "Edit", '#', id: "show_edit_item_form_link",  data: { item_id: @li.id.to_s } %>

		</label>
	</div>
	<% end %>
</div>

<div class="row new_list_item_form_row starts_hidden" id="update_list_item_form-<%= @li.id %>">
	<%= form_for @li, url: account_project_list_item_path(@project.account, @project, @list, @li), method: :put, remote: true, html: {class: "form-inline"} do |f| %>
		<%= hidden_field_tag :action_to_take, "individual_update_info" %>

			<div class="form-group">
			  <%= f.text_field :title, class: "form-control input-sm", id: "todo_item_input", autofocus: true, placeholder: "Add a to-do item" %>
			</div>	
				
			<div class="form-group">
				<%= f.select :user_id, options_for_select(@assignees, @li.user_id), {}, :class => "input-sm form-control assign_user_select" %>
			</div>		
			
			<div class="form-group">
				<%= f.date_field :due, class: "form-control input-sm", id: "todo_due_date_input" %>
			</div>
	
			<div class="form-group">
				<%= f.submit "Update", class: "btn btn-default right1em btn-sm" %>
			</div>
	<% end %>
	
	<div class="new_list_item_cancel_link">
		<%= link_to "Cancel my edits", '#', id: "cancel_edit_item_link", data: { item_id: @li.id.to_s } %> or
		<%= link_to 'Delete this item', account_project_list_item_path(@project.account, @project, @list, @li), method: :delete, remote: true %>.</p>
	</div>	
	
</div>

app/views/items/_new_item_form.html.erb
	<%= form_for @item, url: account_project_list_items_path(@project.account, @project, @list), method: :post, remote: true, html: {class: "form-inline"} do |f| %>
		<%= f.hidden_field :status, value: "active" %>
		<%= f.hidden_field :created_by, value: current_user.id %>
		<%= f.hidden_field :flep, value: rand(1000001..9999999) %>

<div class="row new_list_item_form_row">
			<div class="form-group col-sm-8">
			  <%= f.text_field :title, class: "form-control input-sm", id: "todo_item_input", autofocus: true, placeholder: "Add a to-do item" %>
			</div>	
</div>
<div class="row new_list_item_form_row">				
			<div class="form-group col-sm-2">
				<%= f.select :user_id, options_for_select(@assignees, @item.user_id), {}, :class => "input-sm form-control assign_user_select" %>
			</div>		
			
			<div class="form-group col-sm-2">
				<div class="input-group date_picker_field" id="new_item_date_field" >
					<%= f.text_field :due, class: "form-control input-sm", id: "todo_due_date_input" %>
					<span class="input-group-addon">
						<span class="fa fa-calendar"></i>
					</span>
				</div>
			</div>
	
			<div class="form-group">
				<%= f.submit "Add", class: "btn btn-raisin-green right1em btn-sm" %> or <%= link_to "Cancel", account_project_list_cancel_item_path(@project.account, @project, @list), :remote => true %>
			</div>
			
			<div class="new_list_item_cancel_link">
				
			</div>
	<% end %>
	
	</div>
</div>

app/views/items/cancel.js.erb
$("#add_todo_list_item_form-<%= escape_javascript(@list.id.to_s) %>").empty();
$("#add_todo_item_link-<%= escape_javascript(@list.id.to_s) %>").append("<%= escape_javascript(render 'items/show_new_item_form_link', :locals => {list: @list, project: @project}) %>");

app/views/items/checked.js.erb
$("#list_item_actionable_box-<%= escape_javascript(@li.id.to_s) %>").empty();
$("#completed_todo_items_queue-<%= escape_javascript(@list.id.to_s) %>").css("display", "block");
$("#completed_todo_items_queue-<%= escape_javascript(@list.id.to_s) %>").append("<%= escape_javascript(render '/items/list_item_inactive', locals: {li: @li, project: @project, list: @list}) %>");

app/views/items/create.js.erb
$("#add_todo_list_item_form-<%= escape_javascript(@list.id.to_s) %>").empty();
$("#add_todo_item_link-<%= escape_javascript(@list.id.to_s) %>").append("<%= escape_javascript(render 'items/show_new_item_form_link', :locals => {list: @list, project: @project}) %>");
$("#todo_list_items-<%= escape_javascript(@list.id.to_s) %>").append("<%= escape_javascript(render '/items/list_item_actionable', locals: {project: @project, list: @list, li: @li})%>");
$("#add_todo_list_item_form-<%= escape_javascript(@list.id.to_s) %>").append("<%= escape_javascript(render 'items/new_item_form', :locals => {list: @list, project: @project, item: @item, assigness: @assignees}) %>");
$("#add_todo_item_link-<%= escape_javascript(@list.id.to_s) %>").empty();
$("body").trigger('loadDatePicker');
$("body").trigger('loadSortable');

app/views/items/destroy.js.erb
$("#list_item_actionable_box-<%= escape_javascript(@li.id.to_s) %>").remove();

app/views/items/individual.js.erb
$("#list_item_actionable_box-<%= escape_javascript(@li.id.to_s) %>").empty();
$("#list_item_actionable_box-<%= escape_javascript(@li.id.to_s) %>").append("<%= escape_javascript(render 'list_item_individual') %>");

app/views/items/new.js.erb
$("#add_todo_list_item_form-<%= escape_javascript(@list.id.to_s) %>").append("<%= escape_javascript(render 'items/new_item_form', :locals => {list: @list, project: @project, item: @item, assigness: @assignees}) %>");
$("#add_todo_item_link-<%= escape_javascript(@list.id.to_s) %>").empty();
$("body").trigger('loadDatePicker');

app/views/items/show.html.erb
<h3><%= @project.title %></h3>
<span class="invite_new_collaborator_link">
	<%= link_to "Go to the project page", account_project_path(@project.account, @project) %>
</span>
<div class="completed_page_top">
</div>

<div class="list_item_parent">
	From the list: <%= link_to @list.title, account_project_list_path(@project.account, @project, @list) %> &rarr;
</div>

<div class="item_page_show_todo" id="list_item_actionable_box-<%= @li.id %>">
	
	<%= render 'list_item_individual' %>
	
</div>


<section class="comments_section row">
<div class="col-md-8">	
	
	<h5 class="comments_section_header">
		Have a conversation about this to-do:
	</h5>
	<div id="comments_list">
		<% @existing_comments.each do |ec| %>
			<% if ec.user %>
				<div id="account_comment_container-<%= ec.id %>">
					<%= render partial: '/comments/comment_content_container', locals: {ec: ec} %>
				</div>
			<% end %>	
		<% end %>
	</div>	
	
	<div id="new_comment_form">
		<%= render partial: '/comments/new_comment_form' %>
	</div>
	
</div>	
</section>	

app/views/items/unchecked.js.erb
$("#list_item_actionable_box-<%= escape_javascript(@li.id.to_s) %>").append("<%= escape_javascript(render '/items/list_item_actionable_content', locals: {project: @project, list: @list, li: @li})%>");
$("#list_item_inactive-<%= escape_javascript(@li.id.to_s) %>").remove();

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>