config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do

  devise_for :users, :controllers => { omniauth_callbacks: 'omniauth_callbacks', registrations: 'users/registrations' }
  resources :users, only: [:show, :edit, :update]
  
  get '/accounts/:account_id/projects/:project_id/lists/completed/', to: 'lists#completed', as: "account_project_lists_completed"
  
  resources :accounts, only: [:new, :show, :edit, :create, :update, :index] do
    get 'users', on: :member
    resources :projects do
      resources :conversations
      resources :lists, only: [:create, :update, :destroy, :show, :new] do
        resources :items, only: [:new, :create, :update, :destroy, :show]
      end
    end
    resources :members
    resources :comments
  end
        
  resources :updates      
        
  get '/beta', to: 'pages#beta', as: 'beta'
  get '/help', to: 'pages#help', as: 'help'
  get '/welcome', to: 'accounts#new', as: 'welcome'
  
  resources :subscriptions, only: [:new, :create, :edit, :update]
  
  get '/accounts/:account_id/recently', to: 'accounts#recently', as: 'account_recently'
  get '/accounts/:account_id/createdorder', to: 'accounts#createdorder', as: 'account_createdorder'
  get '/accounts/:account_id/alphabetical', to: 'accounts#alphabetical', as: 'account_alphabetical'

  
  get '/accounts/:account_id/archive', to: 'accounts#archive', as: 'account_project_archive'

  get '/accounts/:account_id/projects/:project_id/cancel', to: 'lists#cancel', as: "account_project_cancel_list", :defaults => { :format => 'js' }
  get '/accounts/:account_id/projects/:project_id/lists/:list_id/cancel', to: 'items#cancel', as: "account_project_list_cancel_item", :defaults => { :format => 'js' }
  
  put '/tasks/sort', to: 'items#sort', as: "sort_tasks"
  
  mount_griddler

  authenticate :user do
    mount Sidekiq::Web => '/sidekiq'
  end

  root 'pages#home'

end

app/models/account.rb
# == Schema Information
#
# Table name: accounts
#
#  id                 :integer          not null, primary key
#  name               :text
#  stripe_customer_id :text
#  active_until       :datetime
#  plan               :text
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#

class Account < ActiveRecord::Base
  include Stripe::Callbacks
  
  has_and_belongs_to_many :users
  accepts_nested_attributes_for :users
  
  has_many :projects
  has_many :members
  
  validates :name, presence: true
  validates :active_until, presence: true
  
  after_customer_subscription_deleted do |subscription, event|
    account = Account.where(stripe_customer_id: subscription.customer)
    account.plan = "canceled"
    account.save
  end
  
end

app/controllers/accounts_controller.rb
include AccountsHelper
class AccountsController < ApplicationController
  before_filter :authenticate_user!, only: [:index, :show, :edit, :update, :archive]
  before_filter :authenticate_account, only: [:show, :edit, :update]
  
  # before_filter :verify_active, only: [:show, :edit, :update]
  
  def index
    #if admin, 
      # show all accounts
    # else
    
    @accounts = current_user.accounts
      
  end
  
  def new
    
    @account = Account.new
    if !current_user
      1.times { @account.users.build }
    end
    
    respond_to do |format|

      format.html { 'new' }
   
    end  
    
  end
  
  def recently
    @account = Account.find(params[:account_id])
    @projs = Project.where(account_id: @account.id, removable: nil).order(:updated_at)
    
    # Same process... what do they have permission to see?
    @projects = []
    @inactive_count = 0
    @projs.each do |p|
      if p.status == "active"
        if p.users.include?(current_user)
          @projects << p 
        end  
      else
        @inactive_count = @inactive_count + 1 if p.status == "garage"
      end  
    end
    
    
    respond_to do |format|
      format.js
    end
  end
  
  def createdorder
    @account = Account.find(params[:account_id])
    @projs = Project.where(account_id: @account.id, removable: nil).order(:created_at)
    
    # Same process... what do they have permission to see?
    @projects = []
    @inactive_count = 0
    @projs.each do |p|
      if p.status == "active"
        if p.users.include?(current_user)
          @projects << p 
        end  
      else
        @inactive_count = @inactive_count + 1 if p.status == "garage"
      end  
    end
    
    
    respond_to do |format|
      format.js { render 'recently' }
    end
  end
  
  def alphabetical
    @account = Account.find(params[:account_id])
    @projs = Project.where(account_id: @account.id, removable: nil).order(:title)
    
    # Same process... what do they have permission to see?
    @projects = []
    @inactive_count = 0
    @projs.each do |p|
      if p.status == "active"
        if p.users.include?(current_user)
          @projects << p 
        end  
      else
        @inactive_count = @inactive_count + 1 if p.status == "garage"
      end  
    end
    
    
    respond_to do |format|
      format.js { render 'recently' }
    end
  end
  
  def create

    @account = Account.new(account_params)
    @account.active_until = Time.now.utc + 2.months
    
    if current_user
      @account.users << current_user
    end
    
    
    respond_to do |format|
      if @account.save
        if !current_user
          sign_in @account.users.last
        end
        
        current_user.time_zone = "Pacific Time (US & Canada)"
        current_user.save 
        
        check_for_and_associate_members_and_accounts(current_user)

        NotificationMailer.new_account_created(@account).deliver_later
        
        #@proj = @account.projects.create(title: current_user.name, removable: "no")
        #@proj.members.create(user_id: current_user.id, account_id: @account.id)
        Member.create(user_id: current_user.id, account_id: @account.id, name: current_user.name)
        
        #create_sample_todo_list_on_permanent_project(@proj)
        create_sample_project_for_new_account(@account)        
        
        format.html { redirect_to root_path, notice: 'All set! Welcome to Raisin.' }
        format.json { render json: root_path, status: :created, location: @account }
      else
        format.html { render action: "new" }
        format.json { render json: @account.errors, status: :unprocessable_entity }
      end
    end
  end

  def show
    @account = Account.find_by_id(params[:id])
    @page_title = " - " + @account.name
    
    # Only display family members to other family members
    @fam_member = Member.where(account_id: @account.id, user_id: current_user.id)
    if @fam_member.count > 0
      @family_members = Member.where(account_id: @account.id).order(:created_at)
      #@family_members = Project.where(account_id: @account.id, removable: "no")
    end  
    
    @projs = Project.where(account_id: @account.id, removable: nil)
    
    # Same process... what do they have permission to see?
    @projects = []
    @inactive_count = 0
    @projs.each do |p|
      if p.status == "active"
        if p.users.include?(current_user)
          @projects << p 
        end  
      else
        @inactive_count = @inactive_count + 1 if p.status == "garage"
      end  
    end
    
    
    session["preferred_account_id"] = @account.id
    
  end

  def edit
    # "Account settings"
  end

  def update
  end
  
  def archive
    # "Project in the garage"
    
    @account = Account.find(params[:account_id])
    @projects = Project.where(account_id: @account.id, removable: nil, status: "garage")
  end
  
  private

    def account_params
      params.require(:account).permit(:name, :plan, :active_until, :users_attributes => [:id, :email, :name, :email_preference, :password, :password_confirmation])
    end
    
    def check_for_and_associate_members_and_accounts(resource)
     # Find all the memberships that we need to associate, and associate them
     members = Member.where(email: resource.email)
     members.each do |m|
       # add the user to any accounts
       a = m.project.account
       if a
         a.users << resource if !a.users.include?(resource)
         a.save!
       end

       # and of course add the user_id to the membership record
       m.user_id = resource.id
       m.save!
     end
    end
    
    def authenticate_account
      account = Account.find(params[:id])
      if !account.users.include?(current_user)
        redirect_to root_path
      end
    end
    
    # Since nobody is paying for Raisin, and the payment API broke for some unknown reason
    # Let's just unhook the payment stuff, which lets me go to free Heroku
    def verify_active
      account = Account.find(params[:id])
      if account.active_until < Time.now.utc
        if account.stripe_customer_id
          flash[:subscription_expired] = "Your subscription has expired! Don't worry, your data is perfectly fine, but you'll need to update your payment information -- it looks like there was a problem charging your card on file."
          session["preferred_account_id"] = account.id
          redirect_to edit_subscription_path
        else
          flash[:subscription_expired] = "Your subscription has expired! Don't worry, your data is perfectly fine, but you'll need to enter your payment information and become a paying subscriber."
          session["preferred_account_id"] = account.id
          redirect_to new_subscription_path
        end
      end
    end
    
end

app/helpers/accounts_helper.rb
module AccountsHelper

  def create_sample_todo_list_on_permanent_project(project)
    list = List.new(
                    title: "You can make to-do lists on family members",
                    status: "active",
                    project_id: project.id
                    )
    list.save!
    
    # now let's add some to-do items
    
    Item.create(
              title: "Usually these are things ABOUT the family member",
              list_id: list.id,
              user_id: current_user.id,
              created_by: current_user.id,
              status: "active"
              )
              
           
           
    Item.create(
              title: "But aren't a project in themselves",
              list_id: list.id,
              user_id: current_user.id,
              created_by: current_user.id,
              status: "active"
              )           

    Item.create(
              title: "Like scheduling a hair cut",
              list_id: list.id,
              user_id: current_user.id,
              created_by: current_user.id,
              status: "active"
              )

  end
  
  def create_sample_project_for_new_account(account)
    
    # First a new project
    
    project = Project.new(
                          title: "Sample Project: Vacation to Hawaii",
                          description: "A project just to get you started",
                          status: "active",
                          account_id: account.id
    )   
    project.save!
    
    # and add the user
    project.members.create(user_id: current_user.id)
   
    # now a list
    
    list = List.new(
                    title: "Booking Travel",
                    status: "active",
                    project_id: project.id
                    )
    list.save!
    
    # now let's add some to-do items
    
    Item.create(
              title: "Research flight options",
              list_id: list.id,
              user_id: current_user.id,
              created_by: current_user.id,
              due: Time.now.utc + 1.week,
              status: "active"
              )
           
           
    Item.create(
              title: "Book flights",
              list_id: list.id,
              user_id: current_user.id,
              created_by: current_user.id,
              due: Time.now.utc + 15.days,
              status: "active"
              )           

    Item.create(
              title: "Reserve a rental car or a shuttle to the hotel",
              list_id: list.id,
              user_id: current_user.id,
              created_by: current_user.id,
              due: Time.now.utc + 15.days,
              status: "active"
              )

  end  

end

app/views/accounts/_active_projects_loop.html.erb
<div class="account_projects_container">
<% @projects.each do |p| %>
	<a class="" href="<%= account_project_path(@account, p) %>">
		<div class="project_box">
			<div class="project_box_title"><%= p.title %></div>
			<div class="project_box_desc"><%= p.description %></div>
		</div>
	</a>
<% end %>	

<% if @family_members %>
	<a class="" href="<%= new_account_project_path(@account) %>">
		<div class="project_box add_new_project">
			<div class="project_box_title">Create a new project </div>
			<div class="project_box_desc new_member_desc">+</div>
		</div>
	</a>
<% end %>

</div>

app/views/accounts/archive.html.erb
<h4>Projects in the garage</h4>

<ul>
	
	<% @projects.each do |p| %>
		<li><%= link_to p.title, account_project_path(@account, p) %></li>
	<% end %>
</ul>

app/views/accounts/edit.html.erb
<h2>Edit your account information</h2>

<p>Coming soon!</p>

app/views/accounts/index.html.erb
<div class="row">
	<div class="col-md-8 col-md-offset-2">

		<p class="lead">It looks like you're part of more than one family! Don't worry, that's just fine ... which one are you looking to work with right now?</p>

		
		<% @accounts.each do |a| %>
			<a class="" href="<%= account_path(a) %>">
				<div class="project_box">
					<div class="project_box_title"><%= a.name %></div>
				</div>
			</a>
		<% end %>
		

	</div>
</div>

app/views/accounts/new.html.erb
<h2>Let's set up your family account.</h2>

<div class="row">
<div class="new_member_page_box col-md-6">

<%= form_for @account, html: {class: "new_account form-horizontal"} do |f| %>

<% if @account.errors.any? %>

    <div id="error_explanation">
      <h5><%= pluralize(@account.errors.count, "error") %> prevented this account from being saved:</h5>

      <ul>
        <% @account.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>

<% end %>



		<%= f.fields_for :users do |a| %>
		<div class="form-group">
		  <%= a.label :name, "Your full name", class: "col-sm-4 control-label" %>
		  <div class="col-sm-7"><%= a.text_field :name, autofocus: true, class: "form-control", placeholder: "Oprah Winfrey" %></div>
		</div>

		<div class="form-group">
		  <%= a.label :email, "Your email", class: "col-sm-4 control-label" %>
			
		  <div class="col-sm-7">
				<%= a.email_field :email, class: "form-control", placeholder: "oprah@oprahmail.com" %>
				<p class="help-block">(This will be your username)</p>
			</div>
		</div>

		<div class="form-group">
		  
			<%= a.label :password, class: "col-sm-4 control-label" %>
			
		  <div class="col-sm-7">
				<%= a.password_field :password, autocomplete: "off", class: "form-control" %>
				<p class="help-block">
		    <em>(8 characters minimum)</em>
		    </p>
			</div>
		</div>
		
		<%= a.hidden_field :email_preference, value: "immediate" %>

		<div class="form-group">
		  <%= a.label :password_confirmation, class: "col-sm-4 control-label" %>
		  <div class="col-sm-7">
				<%= a.password_field :password_confirmation, autocomplete: "off",  class: "form-control" %>
			</div>
		</div>
		
	<% end %>	
		
  <div class="form-group">
    <%= f.label :name, "Your family account name", class: "col-sm-4 control-label" %>
		<%= f.hidden_field :plan, value: "trial" %>
		
    <div class="col-sm-7">
			<%= f.text_field :name, class: "form-control", placeholder: "The Winfreys" %>
			<p class="help-block">(e.g. "The Smiths", or "The Super Coopers")</p>
		</div>
  </div>

  <div class="actions col-sm-offset-4">
    <%= f.submit "Take me to my dashboard", class: "btn btn-default" %>
  </div>
<% end %>



</div>

<div class="new_account_page_sidebar col-md-4 ">

	<% if !current_user %>

	<div class="or_facebook"><%= image_tag 'or.png' %></div>


		<div class="sign_up_facebook">
			<%= link_to image_tag('fblogin.png'), user_omniauth_authorize_path(:facebook) %>
		</div>

	<% end %>	
	
</div>

</div>

app/views/accounts/recently.js.erb
$('#active_projects_loop_div').html("");
$('#active_projects_loop_div').append("<%= escape_javascript(render 'active_projects_loop') %>")

app/views/accounts/show.html.erb
<h1><%= @account.name %></h1>

<% if @family_members %>
	<h4>Family Members</h4>

	<div class="family_member_projects_container">
	<% @family_members.each do |fm| %>
	
		<a class="" href="<%= account_member_path(@account, fm) %>">
			<span class="family_member_box">
				<% if fm.user %>
					<% if fm.user.photo != nil %>
						<% photo_url = fm.user.photo %>
					<% else %>
						<% photo_url = 'nophoto.png' %>
					<% end %>	
				<% else %>
					<% photo_url = 'nophoto.png' %>
				<% end %>
				<div class="project_box_photo"><%= image_tag photo_url %></div>
				<div class="project_box_title"><%= fm.name %></div>
			</span>
		</a>		
	<% end %>

	<a class="" href="<%= new_account_member_path(@account, type: "family") %>">
		<span class="family_member_box add_new_member">
			<div class="project_box_title">Add a new family member </div>
			<div class="project_box_desc new_member_desc">+</div>
		</span>
	</a>	

	</div>

<% end %>

<section class="projects_list">
	<span id="sort_projects">
		Sort: <%= link_to 'When projects were created', account_createdorder_path(@account), remote: true %> or
		<%= link_to 'alphabetically', account_alphabetical_path(@account), remote: true %>
	</span>

	<h4>Projects</h4>

	<div class="row" id="active_projects_loop_div">

		<%= render 'active_projects_loop' %>

	</div>	
	
</section>	
	
	<% if @inactive_count > 0 %>
		<div class="inactive_projects">
			And <a href="<%= account_project_archive_path(@account) %>">
				<%= @inactive_count %> more <%= ' project'.pluralize(@inactive_count) %> in the garage... 
			</a>
		</div>	
	<% end %>
	

app/views/accounts/update.html.erb
<h1>Accounts#update</h1>
<p>Find me in app/views/accounts/update.html.erb</p>